#!/usr/bin/env python
# coding=utf-8
import sys
from os import system as cmd


xml = sys.argv[1]
method = sys.argv[2]
note = sys.argv[3]
command = 'echo "%-40s %-40s %-40s" >> /home/c01b1rd/Notebook/About_Android/View/xmlDetail.txt' % (xml, method, note)
cmd(command)

