#!/usr/bin/env python3
# encoding: utf-8


a = {
    'c': '1',
    'd': '2',
    'e': '3',
    'f': '4',
    'g': '5',
    'a': '6',
    'b': '7'
}

x = ['e', 'a', 'd', 'g', 'b', 'e']

c = {
    '1': 'do',
    '2': 're',
    '3': 'mi',
    '4': 'fa',
    '5': 'sol',
    '6': 'la',
    '7': 'si'
}


for i in x:
    print(i, a[i], c[a[i]])

