#!/usr/bin/env python
# coding=utf-8
from os import system as cmd
import sys


CREATE_MAIN_PATH = "mkdir -p %s" % sys.argv[1]
CREATE_JS_PATH = "mkdir -p %s/Js" % sys.argv[1]
CREATE_CSS_PATH = "mkdir -p %s/Css" % sys.argv[1]
CREATE_IMG_PATH = "mkdir -p %s/Img" % sys.argv[1]

cmd(CREATE_MAIN_PATH)
cmd(CREATE_CSS_PATH)
cmd(CREATE_JS_PATH)
cmd(CREATE_IMG_PATH)

cmd("touch %s/Js/default.js" % sys.argv[1])
cmd("touch %s/Css/default.css" % sys.argv[1])

with( open(sys.argv[1] + "/index.html", "w") ) as file:
    file.writelines("<!DOCTYPE html>\n")
    file.writelines("<html>\n")
    file.writelines("   <head>\n")
    file.writelines("       <title>%s</title>\n" % sys.argv[1])
    file.writelines("       <meta http-equiv=\"Content-Type\" content=\"text/html, charset=utf-8\">\n")
    file.writelines("       <link rel=\"stylesheet\" href=\"Css/default.css\">\n")
    file.writelines("       <link rel=\"icon\" sizes=\"57x57\" href=\"Img/favicon.png\">\n")
    file.writelines("       <script type=\"text/javascript\" src=\"Js/default.js\"></script>\n")
    file.writelines("   </head>\n")
    file.writelines("   <body>\n")
    file.writelines("   </body>\n")
    file.writelines("</html>\n")

