#!/usr/bin/env python
# coding=utf-8
from os import system

fp = open('result.txt', 'r+')
list = fp.readlines()
fp.close()

print '[*] Total host:%d' % len(list)

i = 1
for line in list:
    print '[*] Scaning NO.%d ip...' % i
    cmd = 'nmap ' + line[0:-1] + ' >> info.txt && echo '' >> info.txt'
    system(cmd)
    i += 1

print '[*] Complete.'
