#!/usr/bin/env python
# coding=utf-8
from os import system
import threading

ip_range = str(raw_input('[*]Input the IP range(xx.xx.xx.xx-xx):'))
cmd = 'nmap -sn %s | grep -o "%s.*\..*\..*\..*" > result.txt' % (ip_range, ip_range[0])
system(cmd)
fp = open('result.txt', 'r+')
list = fp.readlines()
fp.close()

print '[*] Total host:%d' % len(list)

def scan(line):
    print '[*]Scanning ' + line[:-1]
    cmd = 'nmap ' + line[0:-1] + ' >> ip_info.txt && echo '' >> ip_info.txt'
    system(cmd)
    print '[*]Complete '+ line[:-1]

for line in list:
    thread = threading.Thread(target=scan, args=(line,))
    thread.start()


